### PR TITLE
Add Nolan, Cowgill

### PR DESCRIPTION
**Pull request by wfmackey**

### CODE REVIEW

**Review by HughParsonage — CHANGES_REQUESTED** [review]
Needs to be tab-separated.

**Comment by wfmackey** [comment]
Sure

**Comment by HughParsonage** [comment]
Also need to change the Higher Education report as it either incorrectly failed to cite James or did not identify him as an editorial author.

**Comment by wfmackey** [comment]
This is for transport report.

**Comment by HughParsonage** [comment]
Also you need to run the `data-raw/put-internal-data.R` script and push the `R/sysdata.rda` file that's produced.

**Pull request merged**
