### PR TITLE
Release status

### PR DESCRIPTION
**Pull request by HughParsonage**

### CODE REVIEW

**Comment by carmelachivers1** [comment]
Shall we merge it?

**Comment by HughParsonage** [comment]
No, not yet. Good work, after the items in my review, try using it inside `checkGrattanReport` to finish.

**Comment by carmelachivers1** [comment]
Where are the items in your review?

**Comment by HughParsonage** [comment]
Ah, because I opened the pull request the reviewing is the wrong way around. I'll close. Afterwards, go to your branch (https://github.com/HughParsonage/grattanReporter/tree/trigger-compile-from-main) and under 'Clone or Download', start a pull request.

**Pull request closed without merging**
